_wandb:
    value:
        cli_version: 0.25.1
        e:
            v1vfkly0t23c2t69znfe39mcibdentbi:
                args:
                    - --epochs
                    - "2"
                    - --batch_size
                    - "2"
                    - --num_workers
                    - "2"
                    - --wandb
                    - ZeroShot-Counting
                    - --title
                    - Test_Baseline
                codePath: FSC_train.py
                codePathLocal: FSC_train.py
                cpu_count: 8
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "512108785664"
                        used: "42071007232"
                email: anhquandinhpham@gmail.com
                executable: C:\ProgramData\miniconda3\envs\AI_env\python.exe
                git:
                    commit: 30f2d0ec6c2926d6c97cb13b9669db274ef9ef56
                    remote: https://github.com/HopooLinZ/VA-Count.git
                gpu: NVIDIA GeForce RTX 3050 6GB Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2560
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3050 6GB Laptop GPU
                      uuid: GPU-c06fd9bd-aad9-fc7e-ece6-312ca2782f4a
                host: DESKTOP-TL9U32D
                memory:
                    total: "21168513024"
                os: Windows-10-10.0.26200-SP0
                program: D:\PROJECTS\Zero-Shot Object Counting\VA-Count\FSC_train.py
                python: CPython 3.10.20
                root: D:\PROJECTS\Zero-Shot Object Counting\VA-Count
                startedAt: "2026-04-13T15:43:40.042301Z"
                writerId: v1vfkly0t23c2t69znfe39mcibdentbi
        m: []
        python_version: 3.10.20
        t:
            "1":
                - 1
                - 41
                - 63
            "2":
                - 1
                - 41
                - 63
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.10.20
            "5": 0.25.1
            "8":
                - 3
            "12": 0.25.1
            "13": windows-amd64
accum_iter:
    value: 1
anno_file:
    value: data\FSC147\annotation_FSC147_pos.json
anno_file_negative:
    value: ./data/FSC147/annotation_FSC147_neg.json
batch_size:
    value: 2
blr:
    value: 0.001
class_file:
    value: data\FSC147\ImageClasses_FSC147.txt
data_path:
    value: ./data/FSC147/
data_split_file:
    value: data\FSC147\Train_Test_Val_FSC_147.json
device:
    value: cuda
dist_on_itp:
    value: false
dist_url:
    value: env://
distributed:
    value: false
do_aug:
    value: true
do_resume:
    value: false
epochs:
    value: 2
im_dir:
    value: data\FSC147\images_384_VarV2
local_rank:
    value: -1
lr:
    value: null
mask_ratio:
    value: 0.5
min_lr:
    value: 0
model:
    value: mae_vit_base_patch16
norm_pix_loss:
    value: false
num_workers:
    value: 2
output_dir:
    value: ./data/out/fim6_dir
pin_mem:
    value: true
resume:
    value: ./data/checkpoint.pth
seed:
    value: 0
start_epoch:
    value: 0
team:
    value: wsense
title:
    value: Test_Baseline
wandb:
    value: ZeroShot-Counting
wandb_id:
    value: null
warmup_epochs:
    value: 10
weight_decay:
    value: 0.05
world_size:
    value: 1
